version: '3'

volumes:
  mysql_data:
    driver: local

services:
  traefik:
    image: traefik
    command: --api --docker
    labels:
      - "traefik.enable=false"
    networks:
      - front-tier
      - back-tier
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    build: .
    image: democracyos/core:latest
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mysql
      - keycloak
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.backend=app"
      - "traefik.docker.network=back-tier"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/api"
      - "traefik.port=3000"
    networks:
      - back-tier
	  

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    # Optionally mount external data directory
    volumes:
      - ~/data3.2:/data/db
    labels:
      - "traefik.enable=false"
    networks:
      - back-tier

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    networks:
      - back-tier
    labels:
      - "traefik.enable=false"

  keycloak:
    image: jboss/keycloak
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      # Same values than the ones declared in mysql service.
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      # Change this seetings
      - KEYCLOAK_USER=admin # VERY IMPORTANT!
      - KEYCLOAK_PASSWORD=Pa55w0rd  # VERY IMPORTANT!
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - mysql
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=keycloak"
      - "traefik.port=8080"
      - "traefik.docker.network=back-tier"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/auth"
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
